apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::803420623185:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-XzaOefntk2lO
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::803420623185:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system